### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ugwulo** [ugwulo/LectureNote#1]
Modify the current README to and include contributing guide

**Comment by sakkshm** [comment]
Hey @ugwulo , I would like to work on this issue!

**Comment by geenva** [comment]
Can I do this?

**Comment by JulietaCaceres** [comment]
Hi I would like to contribute, can I help??

**Comment by wimanshaherath** [comment]
hi! Can I contribute to this?

**Comment by zee-azha** [comment]
hi! can i contribute to this?

**Comment by yashkumar0707** [comment]
Hi, can i please contribute to this?

**Comment by devesh-anand** [comment]
Hi, I am willing to write the full README.md file, but how can I first build and test the code so as to get an idea of how stuff works in LectureNote?

**Comment by geenva** [comment]
Please assign me.

**Comment by devesh-anand** [comment]
I have written a detailed contribution guide, can someone review and recommend changes?
[pull request](https://github.com/ugwulo/LectureNote/pull/12)

**Comment by Girishm99** [comment]
hey i believe that i can do this very efficiently.
