### ISSUE TITLE
Where is Contribute.md? 

### ISSUE THREAD

**Issue by Alesnim** [ugwulo/LectureNote#16]
Hi, in "How to contribute" writes 

>Now open `Contributors.md` file. 

Where is Contributor.md?

**Comment by devesh-anand** [comment]
@Alesnim Maybe you are looking for [CONTRIBUTING.md](https://github.com/ugwulo/LectureNote/blob/main/CONTRIBUTING.md)?

**Comment by Alesnim** [comment]
@devesh-anand But in instruction write
