### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by ugwulo** [ugwulo/LectureNote#2]
write detailed guide on how to contribute to this project 😃

**Comment by jayadevvasudevan** [comment]
can i add the contribute guide??

**Comment by sujata13** [comment]
I want to add Contribution Guide.

**Comment by sandhukaran28** [comment]
Hey, I would like to contribute.

**Comment by ugwulo** [comment]
It's been assigned guys

**Comment by Sudeep152** [comment]
i want to  contribute

**Comment by Dulyaaa** [comment]
I wish to contribute.

**Comment by himik-nainwal** [comment]
On what project we have to contribute???
